name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 0.7.0
homepage: https://github.com/hivedb/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  build: ^3.0.0
  source_gen: ^3.0.0
  hive: ^2.2.3
  analyzer: ^7.0.0
  dartx: ^1.2.0

dev_dependencies:
  test: ^1.26.3
  build_test: any
  build_runner: any
  flutter_lints: ^6.0.0
